name: font_awesome
description: A new Flutter plugin project.
version: 0.0.1
# homepage: 

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
    # -------------------
      some_platform:
        pluginClass: somePluginClass
    # -------------------

  fonts:
      - family: FontAwesomeBrands
        fonts:
          - asset: lib/fonts/fa-brands-400.ttf
            weight: 400
      - family: FontAwesomeRegular
        fonts:
          - asset: lib/fonts/fa-regular-400.ttf
            weight: 400
      - family: FontAwesomeSolid
        fonts:
          - asset: lib/fonts/fa-solid-900.ttf
            weight: 900
      - family: FontAwesomeLight
        fonts:
         - asset: lib/fonts/fa-light-300.ttf
           weight: 300
      - family: FontAwesomeThin
        fonts:
         - asset: lib/fonts/fa-thin-100.ttf
           weight: 100
      - family: FontAwesomeDuotone
        fonts:
         - asset: lib/fonts/fa-duotone-900.ttf
           weight: 900
